#!/usr/bin/python3.4
from elasticsearch import Elasticsearch
es = Elasticsearch()

body = ('{'
    '"mappings": {'
        '"tenant": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"balance": {"type": "float"},'
                '"percent_used": {"type": "float"},'
                '"expiry": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},'
                '"rate_name": {"type": "text"},'
                '"credit": {"type": "float"},'
                '"projects": {"type": "text"},'
                '"payments": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"}'
            '}'
        '},'
        '"project": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"project": {"type": "text"},'
                '"budget_percent": {"type": "float"},'
                '"users": {"type": "text"}'
            '}'
        '},'
        '"user": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"project": {"type": "text"},'
                '"user": {"type": "text"}'
            '}'
        '},'
        '"payment": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"date": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},'
                '"payment": {"type": "float"}'
            '}'
        '},'
        '"rate": {'
            '"properties": {'
                '"rate_name": {"type": "text"},'
                '"default": {"type": "boolean"},'
                '"rules": {"type": "text"}'
            '}'
        '},'
        '"rule": {'
            '"properties": {'
                '"rate_name": {"type": "text"},'
                '"rule": {"type": "text"},'
                '"start": {"type": "text"},'
                '"end": {"type": "text"},'
                '"rate": {"type": "float"}'
            '}'
        '},'
        '"billing": {'
            '"properties": {'
                '"name": {"type": "text"},'
                '"date": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"}'
            '}'
        '}'
    '}'
'}')

es.indices.create(index='dca', body=body) 
