#!/usr/bin/python3.4
from elasticsearch import Elasticsearch
es = Elasticsearch()

body = ('{'
    '"mappings": {'
        '"tenant": {'
            '"properties": {'
                '"name": {"type": "text"},'
                '"balance": {"type": "float"},'
                '"credit": {"type": "float"},'
                '"total_allocated": {"type": "float"},'
                '"projects": {"type": "text"}'
            '}'
        '},'
        '"project": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"project": {"type": "text"},'
                '"budget": {"type": "float"},'
                '"balance": {"type": "float"},'
                '"credit": {"type": "float"},'
                '"requested": {"type": "float"},'
                '"rate": {"type": "float"},'
                '"users": {"type": "text"}'
            '}'
        '},'
        '"rate": {'
            '"properties": {'
                '"rate": {"type": "float"}'
            '}'
        '},'
        '"transaction": {'
            '"properties": {'
                '"project": {"type": "text"},'
                '"user": {"type": "text"},'
                '"start": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},'
                '"end": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},'
                '"runtime": {"type": "integer"},'
                '"cost": {"type": "float"},'
                '"tenant_balance": {"type": "float"}'
            '}'
        '},'
        '"payment": {'
            '"properties": {'
                '"tenant": {"type": "text"},'
                '"date": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"},'
                '"payment": {"type": "float"}'
            '}'
        '}'
    '}'
'}')

es.indices.create(index='dca', body=body)
es.index(index='dca', doc_type='rate', body='{"rate": 50.0}')
