#!/usr/local/bin/python3.5
from subprocess import PIPE, run
import json, sys

def verify(subcommand, success=True):
    print('Executing dca', subcommand)

    command = ['./dca']
    command.extend(subcommand.split(' '))
    result = run(command, stdout=PIPE, stderr=PIPE, universal_newlines=True)

    output = json.loads(result.stdout)
    success_string = 'success' if success else 'failed'

    if (output['status'] != success_string):
        print('Incorrect Status: expected', success_string, 'received', output.status)
        sys.exit(1)
    if (output['status'] == 'error'):
        print('Outputted Error:', output['error'])

verify('wipe')
verify('setup')
verify('tenant add -t t1')
verify('tenant add -t t2 -c 10')
verify('tenant add -t ^', False)
verify('tenant add -t 123456789012345678901234567890123', False)
verify('tenant add -t t1', False)
verify('tenant add -t t100 -c a', False)
verify('tenant add -t t100 -c -1', False)
